- name: Deploy Containers
  hosts: ec2
  become: True
  tasks:
    - name: Install Dependencies (docker)
      yum:
        name: docker
        state: present
    - name: Install Dependencies (pip)
      yum:
        name: python-pip
    - name: Install Dependencies (docker pip module)
      pip: 
        name: docker-py
        state: present
    - name: Get password
      shell: aws ecr get-login-password --region sa-east-1
      register: command_pass
    - name: Login docker repo
      shell: docker login --username AWS --password {{command_pass.stdout}} 419466290453.dkr.ecr.sa-east-1.amazonaws.com
    - name: Pull & Deploy container
      docker_container:
        name: backend
        image: 419466290453.dkr.ecr.sa-east-1.amazonaws.com/rampup-backend:latest
        pull: True
        state: started
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        env:
          db_port: "{{ db_port }}"
          db_entrypoint: "{{ db_entrypoint }}"
          db_user: "{{ db_user }}"
          db_port: "{{ db_port }}"
          db_pass: "{{ db_pass }}" 
          db_name: "{{ db_name }}" 
          port: "{{ backend_port }}"